version: "3.9"

services:
  webserver:
    build:
      args:
        BUILD_ENV: 'prod'
  fastapi:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - ocpq-cache:/ocpq/fastapi/cache
      - ocpq-uploaded:/ocpq/fastapi/data/uploaded

volumes:
  ocpq-cache:
  ocpq-uploaded:
