version: "3.9"

services:
  webserver:
    build:
      context: frontend/
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    ports:
      - "80:3000"
  fastapi:
    build:
      context: backend/
      dockerfile: Dockerfile_fastapi
    depends_on:
      - _backend_base
    ports:
      - "8080:8080"
  _backend_base:
    image: ocpq-backend-base-image
    build:
      context: backend/
      dockerfile: Dockerfile_backend
